name: build

on:
  push:
    branches: [ master ]

jobs:

  publish_x86:
    concurrency: 
      group: ${{ github.ref }}-x86
      cancel-in-progress: true
    permissions:
      packages: write

    runs-on: actuated
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
          repo: alexellis/release-it

      - name: Setup mirror
        uses: self-actuated/hub-mirror@master

      - name: Get Repo Owner
        id: get_repo_owner
        run: echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" > $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Release build
        id: release_build
        uses: docker/build-push-action@v3
        with:
          outputs: "type=registry,push=true"
          platforms: linux/amd64
          build-args: |
            Version=dev
            GitCommit=${{ github.sha }}
          tags: |
            ghcr.io/${{ env.REPO_OWNER }}/release-it:${{ github.sha }}

  # publish_aarch64:
  #   permissions:
  #     packages: write

  #   runs-on: actuated-aarch64
  #   steps:
  #     - uses: actions/checkout@master
  #       with:
  #         fetch-depth: 1
  #         repo: alexellis/release-it

  #     - name: Setup mirror
  #       uses: self-actuated/hub-mirror@master

  #     - name: Get Repo Owner
  #       id: get_repo_owner
  #       run: echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" > $GITHUB_ENV

  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v2
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v2
  #     - name: Login to container Registry
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ github.repository_owner }}
  #         password: ${{ secrets.GITHUB_TOKEN }}
  #         registry: ghcr.io

  #     - name: Release build
  #       id: release_build
  #       uses: docker/build-push-action@v3
  #       with:
  #         outputs: "type=registry,push=true"
  #         platforms: linux/amd64
  #         build-args: |
  #           Version=dev
  #           GitCommit=${{ github.sha }}
  #         tags: |
  #           ghcr.io/${{ env.REPO_OWNER }}/release-it:${{ github.sha }}
